ALTER TABLE `countries` MODIFY COLUMN `name_ar` varchar(255) NOT NULL DEFAULT '';--> statement-breakpoint
ALTER TABLE `countries` MODIFY COLUMN `name_fr` varchar(255) NOT NULL DEFAULT '';--> statement-breakpoint
ALTER TABLE `cities` MODIFY COLUMN `name_ar` varchar(255) NOT NULL DEFAULT '';--> statement-breakpoint
ALTER TABLE `cities` MODIFY COLUMN `name_fr` varchar(255) NOT NULL DEFAULT '';--> statement-breakpoint
ALTER TABLE `zones` MODIFY COLUMN `name_ar` varchar(255) NOT NULL DEFAULT '';--> statement-breakpoint
ALTER TABLE `zones` MODIFY COLUMN `name_fr` varchar(255) NOT NULL DEFAULT '';--> statement-breakpoint
ALTER TABLE `zones` MODIFY COLUMN `displayName_ar` varchar(255) NOT NULL DEFAULT '';--> statement-breakpoint
ALTER TABLE `zones` MODIFY COLUMN `displayName_fr` varchar(255) NOT NULL DEFAULT '';--> statement-breakpoint
ALTER TABLE `cuisines` MODIFY COLUMN `name_ar` varchar(255) NOT NULL DEFAULT '';--> statement-breakpoint
ALTER TABLE `cuisines` MODIFY COLUMN `name_fr` varchar(255) NOT NULL DEFAULT '';--> statement-breakpoint
ALTER TABLE `cuisines` MODIFY COLUMN `description_ar` text NOT NULL DEFAULT ('');--> statement-breakpoint
ALTER TABLE `cuisines` MODIFY COLUMN `description_fr` text NOT NULL DEFAULT ('');--> statement-breakpoint
ALTER TABLE `cuisines` MODIFY COLUMN `meta_description_ar` text NOT NULL DEFAULT ('');--> statement-breakpoint
ALTER TABLE `cuisines` MODIFY COLUMN `meta_description_fr` text NOT NULL DEFAULT ('');--> statement-breakpoint
ALTER TABLE `categories` MODIFY COLUMN `name_ar` varchar(255) NOT NULL DEFAULT '';--> statement-breakpoint
ALTER TABLE `categories` MODIFY COLUMN `name_fr` varchar(255) NOT NULL DEFAULT '';--> statement-breakpoint
ALTER TABLE `categories` MODIFY COLUMN `title_ar` text NOT NULL DEFAULT ('');--> statement-breakpoint
ALTER TABLE `categories` MODIFY COLUMN `title_fr` text NOT NULL DEFAULT ('');--> statement-breakpoint
ALTER TABLE `categories` MODIFY COLUMN `meta_title_ar` text NOT NULL DEFAULT ('');--> statement-breakpoint
ALTER TABLE `categories` MODIFY COLUMN `meta_title_fr` text NOT NULL DEFAULT ('');--> statement-breakpoint
ALTER TABLE `subcategories` MODIFY COLUMN `name_ar` varchar(255) NOT NULL DEFAULT '';--> statement-breakpoint
ALTER TABLE `subcategories` MODIFY COLUMN `name_fr` varchar(255) NOT NULL DEFAULT '';--> statement-breakpoint
ALTER TABLE `adonescategory` MODIFY COLUMN `name_ar` varchar(255) NOT NULL DEFAULT '';--> statement-breakpoint
ALTER TABLE `adonescategory` MODIFY COLUMN `name_fr` varchar(255) NOT NULL DEFAULT '';--> statement-breakpoint
ALTER TABLE `restaurants` MODIFY COLUMN `name_ar` varchar(255) NOT NULL DEFAULT '';--> statement-breakpoint
ALTER TABLE `restaurants` MODIFY COLUMN `name_fr` varchar(255) NOT NULL DEFAULT '';--> statement-breakpoint
ALTER TABLE `restaurants` MODIFY COLUMN `address_ar` text NOT NULL DEFAULT ('');--> statement-breakpoint
ALTER TABLE `restaurants` MODIFY COLUMN `address_fr` text NOT NULL DEFAULT ('');--> statement-breakpoint
ALTER TABLE `addons` MODIFY COLUMN `name_ar` varchar(255) NOT NULL DEFAULT '';--> statement-breakpoint
ALTER TABLE `addons` MODIFY COLUMN `name_fr` varchar(255) NOT NULL DEFAULT '';--> statement-breakpoint
ALTER TABLE `food_variations` MODIFY COLUMN `name_ar` varchar(255) NOT NULL DEFAULT '';--> statement-breakpoint
ALTER TABLE `food_variations` MODIFY COLUMN `name_fr` varchar(255) NOT NULL DEFAULT '';--> statement-breakpoint
ALTER TABLE `variation_options` MODIFY COLUMN `option_name_ar` varchar(255) NOT NULL DEFAULT '';--> statement-breakpoint
ALTER TABLE `variation_options` MODIFY COLUMN `option_name_fr` varchar(255) NOT NULL DEFAULT '';--> statement-breakpoint
ALTER TABLE `food` MODIFY COLUMN `name_ar` varchar(255) NOT NULL DEFAULT '';--> statement-breakpoint
ALTER TABLE `food` MODIFY COLUMN `name_fr` varchar(255) NOT NULL DEFAULT '';--> statement-breakpoint
ALTER TABLE `food` MODIFY COLUMN `description_ar` text NOT NULL DEFAULT ('');--> statement-breakpoint
ALTER TABLE `food` MODIFY COLUMN `description_fr` text NOT NULL DEFAULT ('');--> statement-breakpoint
ALTER TABLE `payment_methods` MODIFY COLUMN `name_ar` varchar(100) NOT NULL DEFAULT '';--> statement-breakpoint
ALTER TABLE `payment_methods` MODIFY COLUMN `name_fr` varchar(100) NOT NULL DEFAULT '';--> statement-breakpoint
ALTER TABLE `payment_methods` MODIFY COLUMN `description_ar` varchar(255) NOT NULL DEFAULT '';--> statement-breakpoint
ALTER TABLE `payment_methods` MODIFY COLUMN `description_fr` varchar(255) NOT NULL DEFAULT '';--> statement-breakpoint
ALTER TABLE `branches` MODIFY COLUMN `name_ar` varchar(255) NOT NULL DEFAULT '';--> statement-breakpoint
ALTER TABLE `branches` MODIFY COLUMN `name_fr` varchar(255) NOT NULL DEFAULT '';--> statement-breakpoint
ALTER TABLE `branches` MODIFY COLUMN `address_ar` text NOT NULL DEFAULT ('');--> statement-breakpoint
ALTER TABLE `branches` MODIFY COLUMN `address_fr` text NOT NULL DEFAULT ('');